### ISSUE TITLE
Errors in WICImage.cls (tB v494)

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WICDemo64#1]
Was looking for improved PNG support in tB so downloaded your 64-bit version of WICDemo for a test run. Thanks for providing this!

When I opened your tB Project in tB v494, I see 4 errors. They are all similar to this one (whenever passing a 0& for WICRect type):

![image](https://github.com/fafalone/WICDemo64/assets/26237126/5e60ec13-a819-4d96-a5b0-8c540c21894a)

Thanks again,

Mike

**Comment by fafalone** [comment]
Sorry about that, I must have changed those in WinDevLib at some point and forgot to update this project too.

I've updated the repo files with the fix for the 4 WICRect arguments (they should now be `vbNullPtr` instead of `0&`), and one other bug: In the line in your screenshot, it should be `ByVal pvImageBits`.

Updated WinDevLib to the latest version and confirmed it's now working.

Thanks for reporting, any other issues don't hesitate to reopen or make a new issue.
